# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  test_backend:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.comcaptainkovalsky/shop
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...

  backend:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.comcaptainkovalsky/shop
    steps:
      - checkout
      - run: go get -v -d ./...
      - run: bash scripts/build.bash
      - run:
          name: Compress Artifacts
          command: tar -cvzf back.tar -C dist .
      - store_artifacts:
          path: back.tar
      - persist_to_workspace:
          root: .
          paths:
            - scripts/deploy.sh
            - cv.json
            - scripts/deploy-services.bash
            - back.tar

  deploy:
    docker:
      - image: cimg/base:2020.01
    steps:
      - attach_workspace:
          at: workspace
      - add_ssh_keys:
          fingerprints:
            - "3a:49:3d:97:5f:6b:54:79:0c:32:0b:5c:28:b5:b2:a3"
      - run:
          name: "Configure SSH"
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
            sudo apt-get update
            sudo apt -y install rsync sshpass
      - run:
          name: "Deploy to Digital Ocean"
          command: |
            ls -lh workspace
            sh workspace/scripts/deploy.sh
workflows:
  version: 2
  build:
    jobs:
      - test_backend
      - backend:
          requires:
            - test_backend
      - hold:
          type: approval
          requires:
            - backend
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
