# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  buildBE:
    docker:
      # specify the version
      - image: circleci/golang:1.9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.comcaptainkovalsky/shop
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: bash scripts/build.bash
      - store_artifacts:
          path: /dist

  buildFE:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          cd frontend && ls -la
      - restore_cache: # special step to restore the dependency cache
            # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
            keys:
              - v1-repo-{{ checksum "frontend/package-lock.json" }}
      - run:
          name: Install dependencies with NPM
          command: cd frontend && npm ci # replace with `yarn install` if using yarn

      - save_cache: # special step to save the dependency cache
          key: v1-repo-{{ checksum "frontend/package-lock.json" }}
          paths:
            - "frontend/node_modules"
      - run:
          cd frontend && npm run build
      - store_artifacts:
          path: /dist
workflows:
  version: 2
  build:
    jobs:
      - "buildBE"
      - "buildFE"
